modLoader="javafml"
loaderVersion="[28,]"
logoFile="logo.png"
authors="Pugz"

[[mods]]
    modId="florist"
    version="1.1.5a"
    displayName="Florist"
    description='''
    Put more items in Flower Pots!
    '''